title: "Hatice Karataş"
description: "Portfolio showcasing projects in AI, medical imaging, and autonomous systems."
url: "https://haticekaratas.github.io"
baseurl: ""
theme: jekyll-theme-architect

author:
  name: Hatice Karataş
  email: karatashatice209@gmail.com

plugins:
  - jekyll-feed
