title: "Hatice Karataş"
#description: text below image
show_downloads: true
theme: jekyll-theme-architect
baseurl: "/haticekaratas.github.io"

collections:
  posts:
    output: true
    permalink: /:categories/:title/

