title: "Hatice Karataş"
baseurl: "/haticekaratas.github.io"
#description: text below image
show_downloads: true
theme: jekyll-theme-architect

collections:
  posts:
    output: true
    permalink: /:categories/:title/


